/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

#include "IntegerType.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);

// 用于生成唯一标签的计数器
static int unique_label_counter = 0;


#line 94 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MiniCBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_INT = 5,                      /* T_INT  */
  YYSYMBOL_T_VOID = 6,                     /* T_VOID  */
  YYSYMBOL_T_RETURN = 7,                   /* T_RETURN  */
  YYSYMBOL_T_IF = 8,                       /* T_IF  */
  YYSYMBOL_T_ELSE = 9,                     /* T_ELSE  */
  YYSYMBOL_T_WHILE = 10,                   /* T_WHILE  */
  YYSYMBOL_T_BREAK = 11,                   /* T_BREAK  */
  YYSYMBOL_T_CONTINUE = 12,                /* T_CONTINUE  */
  YYSYMBOL_T_SEMICOLON = 13,               /* T_SEMICOLON  */
  YYSYMBOL_T_L_PAREN = 14,                 /* T_L_PAREN  */
  YYSYMBOL_T_R_PAREN = 15,                 /* T_R_PAREN  */
  YYSYMBOL_T_L_BRACE = 16,                 /* T_L_BRACE  */
  YYSYMBOL_T_R_BRACE = 17,                 /* T_R_BRACE  */
  YYSYMBOL_T_L_BRACKET = 18,               /* T_L_BRACKET  */
  YYSYMBOL_T_R_BRACKET = 19,               /* T_R_BRACKET  */
  YYSYMBOL_T_COMMA = 20,                   /* T_COMMA  */
  YYSYMBOL_T_ASSIGN = 21,                  /* T_ASSIGN  */
  YYSYMBOL_T_SUB = 22,                     /* T_SUB  */
  YYSYMBOL_T_ADD = 23,                     /* T_ADD  */
  YYSYMBOL_T_MUL = 24,                     /* T_MUL  */
  YYSYMBOL_T_DIV = 25,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 26,                     /* T_MOD  */
  YYSYMBOL_T_GT = 27,                      /* T_GT  */
  YYSYMBOL_T_GE = 28,                      /* T_GE  */
  YYSYMBOL_T_LT = 29,                      /* T_LT  */
  YYSYMBOL_T_LE = 30,                      /* T_LE  */
  YYSYMBOL_T_EQ = 31,                      /* T_EQ  */
  YYSYMBOL_T_NE = 32,                      /* T_NE  */
  YYSYMBOL_T_AND = 33,                     /* T_AND  */
  YYSYMBOL_T_OR = 34,                      /* T_OR  */
  YYSYMBOL_T_NOT = 35,                     /* T_NOT  */
  YYSYMBOL_YYACCEPT = 36,                  /* $accept  */
  YYSYMBOL_CompileUnit = 37,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 38,                   /* FuncDef  */
  YYSYMBOL_FormalParamList = 39,           /* FormalParamList  */
  YYSYMBOL_FormalParam = 40,               /* FormalParam  */
  YYSYMBOL_Block = 41,                     /* Block  */
  YYSYMBOL_BlockItemList = 42,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 43,                 /* BlockItem  */
  YYSYMBOL_VarDecl = 44,                   /* VarDecl  */
  YYSYMBOL_VarDeclExpr = 45,               /* VarDeclExpr  */
  YYSYMBOL_VarDef = 46,                    /* VarDef  */
  YYSYMBOL_BasicType = 47,                 /* BasicType  */
  YYSYMBOL_Statement = 48,                 /* Statement  */
  YYSYMBOL_Expr = 49,                      /* Expr  */
  YYSYMBOL_OrExpr = 50,                    /* OrExpr  */
  YYSYMBOL_AndExpr = 51,                   /* AndExpr  */
  YYSYMBOL_RelExp = 52,                    /* RelExp  */
  YYSYMBOL_RelOp = 53,                     /* RelOp  */
  YYSYMBOL_AddExp = 54,                    /* AddExp  */
  YYSYMBOL_AddOp = 55,                     /* AddOp  */
  YYSYMBOL_MulExp = 56,                    /* MulExp  */
  YYSYMBOL_MulOp = 57,                     /* MulOp  */
  YYSYMBOL_UnaryExp = 58,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 59,                /* PrimaryExp  */
  YYSYMBOL_RealParamList = 60,             /* RealParamList  */
  YYSYMBOL_LVal = 61,                      /* LVal  */
  YYSYMBOL_ArrayDimensions = 62,           /* ArrayDimensions  */
  YYSYMBOL_ArrayAccess = 63                /* ArrayAccess  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  8
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   189

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  36
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  28
/* YYNRULES -- Number of rules.  */
#define YYNRULES  81
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  139

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   290


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,    89,    89,    97,   103,   108,   115,   133,   152,   156,
     163,   180,   200,   206,   217,   222,   231,   235,   246,   252,
     283,   316,   324,   336,   345,   346,   353,   359,   363,   369,
     375,   381,   387,   401,   416,   433,   437,   445,   452,   455,
     458,   465,   468,   471,   480,   485,   490,   498,   501,   504,
     507,   510,   513,   522,   527,   532,   540,   543,   552,   557,
     562,   570,   573,   576,   586,   592,   598,   604,   620,   639,
     643,   649,   661,   665,   672,   681,   688,   693,   698,   703,
     711,   719
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_INT", "T_VOID", "T_RETURN", "T_IF", "T_ELSE", "T_WHILE", "T_BREAK",
  "T_CONTINUE", "T_SEMICOLON", "T_L_PAREN", "T_R_PAREN", "T_L_BRACE",
  "T_R_BRACE", "T_L_BRACKET", "T_R_BRACKET", "T_COMMA", "T_ASSIGN",
  "T_SUB", "T_ADD", "T_MUL", "T_DIV", "T_MOD", "T_GT", "T_GE", "T_LT",
  "T_LE", "T_EQ", "T_NE", "T_AND", "T_OR", "T_NOT", "$accept",
  "CompileUnit", "FuncDef", "FormalParamList", "FormalParam", "Block",
  "BlockItemList", "BlockItem", "VarDecl", "VarDeclExpr", "VarDef",
  "BasicType", "Statement", "Expr", "OrExpr", "AndExpr", "RelExp", "RelOp",
  "AddExp", "AddOp", "MulExp", "MulOp", "UnaryExp", "PrimaryExp",
  "RealParamList", "LVal", "ArrayDimensions", "ArrayAccess", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-127)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
      72,  -127,  -127,    52,  -127,  -127,   -11,    16,  -127,  -127,
    -127,  -127,    46,    80,  -127,    68,  -127,    34,    23,    31,
      37,    71,    -7,  -127,   114,    89,  -127,  -127,    86,    31,
      31,    31,  -127,    88,   107,   116,    53,   104,   111,  -127,
    -127,   132,    35,    11,  -127,    71,    72,   136,  -127,   117,
      31,   149,  -127,  -127,    31,    31,    31,  -127,  -127,  -127,
    -127,  -127,  -127,    31,    31,  -127,  -127,    31,    31,  -127,
    -127,  -127,    31,    31,    31,    31,   146,  -127,   120,   152,
     153,   155,   156,  -127,  -127,  -127,    57,  -127,  -127,    46,
    -127,   157,   150,  -127,  -127,    37,  -127,  -127,    73,   154,
    -127,   139,   129,   139,   129,   140,   140,   111,   111,  -127,
    -127,   158,  -127,  -127,   161,    31,    31,  -127,  -127,  -127,
    -127,  -127,    31,  -127,    31,  -127,  -127,  -127,   160,   163,
     166,  -127,   103,   103,  -127,   167,  -127,   103,  -127
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    24,    25,     0,     2,     3,     0,     0,     1,     4,
       5,    18,     0,    21,    19,    21,    20,     0,     0,     0,
      22,     0,     0,     8,     0,     0,    77,    70,    74,     0,
       0,     0,    23,    37,    38,    41,    44,    53,    58,    64,
      71,    75,     0,     0,     6,     0,     0,    10,    76,     0,
       0,     0,    65,    66,     0,     0,     0,    47,    48,    49,
      50,    51,    52,     0,     0,    57,    56,     0,     0,    61,
      62,    63,     0,     0,     0,     0,     0,    79,     0,     0,
       0,     0,     0,    31,    12,    29,     0,    14,    17,     0,
      16,     0,    71,     7,     9,    11,    67,    72,     0,     0,
      69,    40,    43,    39,    42,    46,    45,    55,    54,    60,
      59,     0,    78,    27,     0,     0,     0,    35,    36,    13,
      15,    30,     0,    68,     0,    80,    81,    26,     0,     0,
       0,    73,     0,     0,    28,    32,    34,     0,    33
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -127,  -127,   177,  -127,   135,    -9,  -127,    96,    99,  -127,
     171,   -14,  -126,   -19,  -127,    97,   -12,   148,    45,   151,
     -31,   147,   -26,  -127,  -127,   -42,   142,  -127
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
       0,     3,     4,    22,    23,    85,    86,    87,    88,     6,
      14,     7,    90,    91,    33,    34,    35,    64,    36,    68,
      37,    73,    38,    39,    98,    40,    20,    41
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      32,    92,    11,    24,    52,    53,   135,   136,    45,    12,
      51,   138,    44,    46,    27,    28,     1,     2,    78,    79,
      13,    80,    81,    82,    83,    29,    25,    43,    84,    89,
      97,    99,    24,    30,    27,    28,    93,   107,    76,     1,
       2,   108,    26,   102,    92,    29,    31,   109,   110,    21,
      15,   104,     8,    30,    77,    42,   111,     1,     2,   114,
      27,    28,     1,     2,    78,    79,    31,    80,    81,    82,
      83,    29,    89,    43,   119,    65,    66,     1,     2,    30,
      57,    58,    59,    60,    61,    62,    18,    43,   123,    19,
      92,    92,    31,   124,    17,    92,   128,   129,    18,     5,
      49,    19,    10,   130,    50,   131,    27,    28,    48,   105,
      78,    79,   106,    80,    81,    82,    83,    29,    47,    43,
      27,    28,    54,    27,    28,    30,    65,    66,    69,    70,
      71,    29,    96,   113,    29,    69,    70,    71,    31,    30,
      55,    56,    30,    57,    58,    59,    60,    61,    62,    63,
      75,   101,    31,   103,    18,    31,    57,    58,    59,    60,
      61,    62,    65,    66,   100,   112,   115,   116,   117,   118,
     121,   122,    55,   125,   127,   132,   137,   126,   133,   134,
       9,    94,   120,    16,    67,    74,     0,     0,    72,    95
};

static const yytype_int16 yycheck[] =
{
      19,    43,    13,    17,    30,    31,   132,   133,    15,    20,
      29,   137,    21,    20,     3,     4,     5,     6,     7,     8,
       4,    10,    11,    12,    13,    14,     3,    16,    17,    43,
      49,    50,    46,    22,     3,     4,    45,    68,     3,     5,
       6,    72,    19,    55,    86,    14,    35,    73,    74,    15,
       4,    63,     0,    22,    19,    18,    75,     5,     6,    78,
       3,     4,     5,     6,     7,     8,    35,    10,    11,    12,
      13,    14,    86,    16,    17,    22,    23,     5,     6,    22,
      27,    28,    29,    30,    31,    32,    18,    16,    15,    21,
     132,   133,    35,    20,    14,   137,   115,   116,    18,     0,
      14,    21,     3,   122,    18,   124,     3,     4,    19,    64,
       7,     8,    67,    10,    11,    12,    13,    14,     4,    16,
       3,     4,    34,     3,     4,    22,    22,    23,    24,    25,
      26,    14,    15,    13,    14,    24,    25,    26,    35,    22,
      33,    34,    22,    27,    28,    29,    30,    31,    32,    33,
      18,    54,    35,    56,    18,    35,    27,    28,    29,    30,
      31,    32,    22,    23,    15,    19,    14,    14,    13,    13,
      13,    21,    33,    19,    13,    15,     9,    19,    15,    13,
       3,    46,    86,    12,    36,    38,    -1,    -1,    37,    47
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     5,     6,    37,    38,    44,    45,    47,     0,    38,
      44,    13,    20,     4,    46,     4,    46,    14,    18,    21,
      62,    15,    39,    40,    47,     3,    19,     3,     4,    14,
      22,    35,    49,    50,    51,    52,    54,    56,    58,    59,
      61,    63,    18,    16,    41,    15,    20,     4,    19,    14,
      18,    49,    58,    58,    34,    33,    34,    27,    28,    29,
      30,    31,    32,    33,    53,    22,    23,    53,    55,    24,
      25,    26,    55,    57,    57,    18,     3,    19,     7,     8,
      10,    11,    12,    13,    17,    41,    42,    43,    44,    47,
      48,    49,    61,    41,    40,    62,    15,    49,    60,    49,
      15,    51,    52,    51,    52,    54,    54,    56,    56,    58,
      58,    49,    19,    13,    49,    14,    14,    13,    13,    17,
      43,    13,    21,    15,    20,    19,    19,    13,    49,    49,
      49,    49,    15,    15,    13,    48,    48,     9,    48
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    36,    37,    37,    37,    37,    38,    38,    39,    39,
      40,    40,    41,    41,    42,    42,    43,    43,    44,    45,
      45,    46,    46,    46,    47,    47,    48,    48,    48,    48,
      48,    48,    48,    48,    48,    48,    48,    49,    50,    50,
      50,    51,    51,    51,    52,    52,    52,    53,    53,    53,
      53,    53,    53,    54,    54,    54,    55,    55,    56,    56,
      56,    57,    57,    57,    58,    58,    58,    58,    58,    59,
      59,    59,    60,    60,    61,    61,    62,    62,    62,    62,
      63,    63
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     5,     6,     1,     3,
       2,     3,     2,     3,     1,     2,     1,     1,     2,     2,
       3,     1,     2,     3,     1,     1,     3,     2,     4,     1,
       2,     1,     5,     7,     5,     2,     2,     1,     1,     3,
       3,     1,     3,     3,     1,     3,     3,     1,     1,     1,
       1,     1,     1,     1,     3,     3,     1,     1,     1,     3,
       3,     1,     1,     1,     1,     2,     2,     3,     4,     3,
       1,     1,     1,     3,     1,     1,     3,     2,     4,     3,
       4,     4
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 89 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                      {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));

		// 设置到全局变量中
		ast_root = (yyval.node);
	}
#line 1253 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 3: /* CompileUnit: VarDecl  */
#line 97 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
		ast_root = (yyval.node);
	}
#line 1264 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 103 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {

		// 把函数定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1274 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit VarDecl  */
#line 108 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// 把变量定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1283 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 6: /* FuncDef: BasicType T_ID T_L_PAREN T_R_PAREN Block  */
#line 115 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                    {

		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-4].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-3].var_id);

		// 函数体节点即Block，即$5
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点没有，设置为空指针
		ast_node * formalParamsNode = nullptr;

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参(实际上无)
		// create_func_def函数内会释放funcId中指向的标识符空间，切记，之后不要再释放，之前一定要是通过strdup函数或者malloc分配的空间
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1306 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 7: /* FuncDef: BasicType T_ID T_L_PAREN FormalParamList T_R_PAREN Block  */
#line 133 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                                   {
		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-5].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-4].var_id);

		// 函数体节点即Block，即$6
		ast_node * blockNode = (yyvsp[0].node);

		// 形参节点，即$4
		ast_node * formalParamsNode = (yyvsp[-2].node);

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1327 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 8: /* FormalParamList: FormalParam  */
#line 152 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// 创建形参列表节点，并把当前的形参节点加入
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
	}
#line 1336 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 9: /* FormalParamList: FormalParamList T_COMMA FormalParam  */
#line 156 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                              {
		// 左递归增加形参
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 1345 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 10: /* FormalParam: BasicType T_ID  */
#line 163 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                             {
		// 形参类型
		type_attr paramType = (yyvsp[-1].type);

		// 形参名
		var_id_attr paramId = (yyvsp[0].var_id);

		// 创建形参节点
		ast_node * type_node = create_type_node(paramType);
		ast_node * id_node = ast_node::New(std::string(paramId.id), paramId.lineno);
		
		// 对于字符型字面量的字符串空间需要释放
		free(paramId.id);
		
		// 创建形参节点，包含类型和名称
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAM, type_node, id_node);
	}
#line 1367 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 11: /* FormalParam: BasicType T_ID ArrayDimensions  */
#line 180 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                         {
		// 数组形参定义
		type_attr paramType = (yyvsp[-2].type);
		var_id_attr paramId = (yyvsp[-1].var_id);
		
		// 创建形参节点
		ast_node * type_node = create_type_node(paramType);
		ast_node * id_node = ast_node::New(std::string(paramId.id), paramId.lineno);
		
		// 对于字符型字面量的字符串空间需要释放
		free(paramId.id);
		
		// 创建数组形参节点，包含类型、名称和维度信息
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAM_ARRAY, type_node, id_node, (yyvsp[0].node));
	}
#line 1387 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 12: /* Block: T_L_BRACE T_R_BRACE  */
#line 200 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                            {
		// 语句块没有语句

		// 为了方便创建一个空的Block节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BLOCK);
	}
#line 1398 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 13: /* Block: T_L_BRACE BlockItemList T_R_BRACE  */
#line 206 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                            {
		// 语句块含有语句

		// BlockItemList归约时内部创建Block节点，并把语句加入，这里不创建Block节点
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1409 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 14: /* BlockItemList: BlockItem  */
#line 217 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                          {
		// 第一个左侧的孩子节点归约成Block节点，后续语句可持续作为孩子追加到Block节点中
		// 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node));
	}
#line 1419 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 15: /* BlockItemList: BlockItemList BlockItem  */
#line 222 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                  {
		// 把BlockItem归约的节点加入到BlockItemList的节点中
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1428 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 16: /* BlockItem: Statement  */
#line 231 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                       {
		// 语句节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1437 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 17: /* BlockItem: VarDecl  */
#line 235 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
		// 变量声明节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1446 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 18: /* VarDecl: VarDeclExpr T_SEMICOLON  */
#line 246 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                  {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1454 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 19: /* VarDeclExpr: BasicType VarDef  */
#line 252 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {

		ast_node * type_node = create_type_node((yyvsp[-1].type)); // $1 is BasicType
        ast_node * def_result_node = (yyvsp[0].node);             // $2 is from VarDef
        ast_node * id_or_array_node;
        ast_node * init_expr_node = nullptr;

        if (def_result_node->node_type == ast_operator_type::AST_OP_ASSIGN) {
            // It's an ID with an initializer, packed in a temporary ASSIGN node
            id_or_array_node = def_result_node->sons[0];
            init_expr_node = def_result_node->sons[1];
            def_result_node->sons.clear(); // Detach children before deleting parent
            ast_node::Delete(def_result_node); // Delete the temporary ASSIGN node
        } else {
            // It's a simple ID or an ARRAY_DEF
            id_or_array_node = def_result_node;
        }

        ast_node * decl_node; // This will be AST_OP_VAR_DECL
        if (init_expr_node) {
            decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, id_or_array_node, init_expr_node);
        } else {
            decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, id_or_array_node);
        }
        decl_node->type = type_node->type; // Set the type on the AST_OP_VAR_DECL node itself
        
        (yyval.node) = create_var_decl_stmt_node(decl_node);
        if ((yyval.node)) { // Ensure create_var_decl_stmt_node returned a node
             ((yyval.node))->type = type_node->type; // Explicitly set type for the statement node
        }
	}
#line 1490 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 20: /* VarDeclExpr: VarDeclExpr T_COMMA VarDef  */
#line 283 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                     {

        Type * common_type_for_stmt = (yyvsp[-2].node)->type; // Corrected type to Type*

        ast_node * def_result_node = (yyvsp[0].node); // Result from the current VarDef
        ast_node * id_or_array_node;
        ast_node * init_expr_node = nullptr;

        if (def_result_node->node_type == ast_operator_type::AST_OP_ASSIGN) {
            id_or_array_node = def_result_node->sons[0];
            init_expr_node = def_result_node->sons[1];
            def_result_node->sons.clear();
            ast_node::Delete(def_result_node);
        } else {
            id_or_array_node = def_result_node;
        }

        // Each AST_OP_VAR_DECL needs its own type node instance, created from the common Type*
        ast_node * current_type_node = ast_node::New(common_type_for_stmt); // Should now call ast_node::New(Type*)

        ast_node * decl_node; // This is an AST_OP_VAR_DECL for the current variable
        if (init_expr_node) {
            decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, current_type_node, id_or_array_node, init_expr_node);
        } else {
            decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, current_type_node, id_or_array_node);
        }
        decl_node->type = current_type_node->type; // Set type for this specific VAR_DECL

        (yyval.node) = (yyvsp[-2].node)->insert_son_node(decl_node); // Add to existing AST_OP_DECL_STMT
	}
#line 1525 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 21: /* VarDef: T_ID  */
#line 316 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
              {
		// 变量ID

		(yyval.node) = ast_node::New(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 1538 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 22: /* VarDef: T_ID ArrayDimensions  */
#line 324 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                               {
		// 数组变量定义
		
		// 创建变量名节点
		ast_node * var_node = ast_node::New(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
		
		// 对于字符型字面量的字符串空间需要释放
		free((yyvsp[-1].var_id).id);
		
		// 创建数组定义节点，包含变量名和维度信息
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DEF, var_node, (yyvsp[0].node));
	}
#line 1555 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 23: /* VarDef: T_ID T_ASSIGN Expr  */
#line 336 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                         { // New production for initialization
        ast_node * id_node = ast_node::New(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
        free((yyvsp[-2].var_id).id); // free the strduped id
        // Temporarily use AST_OP_ASSIGN to package id_node and expr_node ($3)
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node));
    }
#line 1566 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 24: /* BasicType: T_INT  */
#line 345 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                 { (yyval.type) = (yyvsp[0].type); }
#line 1572 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 25: /* BasicType: T_VOID  */
#line 346 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  { (yyval.type) = (yyvsp[0].type); }
#line 1578 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 26: /* Statement: T_RETURN Expr T_SEMICOLON  */
#line 353 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                      {
		// 返回语句

		// 创建返回节点AST_OP_RETURN，其孩子为Expr，即$2
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_RETURN, (yyvsp[-1].node));
	}
#line 1589 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 27: /* Statement: T_RETURN T_SEMICOLON  */
#line 359 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                               {
		// 创建一个没有子节点的返回节点 AST_OP_RETURN
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_RETURN);
	}
#line 1598 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 28: /* Statement: LVal T_ASSIGN Expr T_SEMICOLON  */
#line 363 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                         {
		// 赋值语句

		// 创建一个AST_OP_ASSIGN类型的中间节点，孩子为LVal($1)和Expr($3)
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1609 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 29: /* Statement: Block  */
#line 369 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		// 语句块

		// 内部已创建block节点，直接传递给Statement
		(yyval.node) = (yyvsp[0].node);
	}
#line 1620 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 30: /* Statement: Expr T_SEMICOLON  */
#line 375 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                           {
		// 表达式语句

		// 内部已创建表达式，直接传递给Statement
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1631 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 31: /* Statement: T_SEMICOLON  */
#line 381 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                      {
		// 空语句

		// 直接返回空指针，需要再把语句加入到语句块时要注意判断，空语句不要加入
		(yyval.node) = nullptr;
	}
#line 1642 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 32: /* Statement: T_IF T_L_PAREN Expr T_R_PAREN Statement  */
#line 387 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                  {
		// IF语句
		
		// 为条件表达式生成唯一的真假出口标签
		std::string true_label = ".L" + std::to_string(unique_label_counter++);
		std::string false_label = ".L" + std::to_string(unique_label_counter++);
		
		// 设置条件表达式的真假出口标签
		(yyvsp[-2].node)->true_label = true_label;  // 真出口，执行语句
		(yyvsp[-2].node)->false_label = false_label; // 假出口，跳过语句
		
		// 创建IF语句节点，包含条件表达式和语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_IF, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1661 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 33: /* Statement: T_IF T_L_PAREN Expr T_R_PAREN Statement T_ELSE Statement  */
#line 401 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                                   {
		// IF-ELSE语句
		
		// 为条件表达式生成唯一的真假出口标签
		std::string true_label = ".L" + std::to_string(unique_label_counter++);
		std::string false_label = ".L" + std::to_string(unique_label_counter++);
		std::string end_label = ".L" + std::to_string(unique_label_counter++);
		
		// 设置条件表达式的真假出口标签
		(yyvsp[-4].node)->true_label = true_label;  // 真出口，执行IF语句
		(yyvsp[-4].node)->false_label = false_label; // 假出口，执行ELSE语句
		
		// 创建IF-ELSE语句节点，包含条件表达式、IF语句和ELSE语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_IF_ELSE, (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1681 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 34: /* Statement: T_WHILE T_L_PAREN Expr T_R_PAREN Statement  */
#line 416 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                     {
		// WHILE循环语句
		
		// 为条件表达式生成唯一的循环入口、循环体和循环结束标签
		std::string loop_start_label_parser_hint = ".L" + std::to_string(unique_label_counter++);
		std::string loop_body_label_parser_hint = ".L" + std::to_string(unique_label_counter++);
		std::string loop_end_label_parser_hint = ".L" + std::to_string(unique_label_counter++);
		
		// 设置条件表达式的真假出口标签 (these are hints for the condition node itself)
		(yyvsp[-2].node)->true_label = loop_body_label_parser_hint;
		(yyvsp[-2].node)->false_label = loop_end_label_parser_hint;
		
		// 创建WHILE语句节点，包含条件表达式和循环体语句
		ast_node* while_node = create_contain_node(ast_operator_type::AST_OP_WHILE, (yyvsp[-2].node), (yyvsp[0].node));
		
		(yyval.node) = while_node;
	}
#line 1703 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 35: /* Statement: T_BREAK T_SEMICOLON  */
#line 433 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// BREAK语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BREAK);
	}
#line 1712 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 36: /* Statement: T_CONTINUE T_SEMICOLON  */
#line 437 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                 {
		// CONTINUE语句
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONTINUE);
	}
#line 1721 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 37: /* Expr: OrExpr  */
#line 445 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
              {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1729 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 38: /* OrExpr: AndExpr  */
#line 452 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                 {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1737 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 39: /* OrExpr: AndExpr T_OR AndExpr  */
#line 455 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                               {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_OR, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1745 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 40: /* OrExpr: OrExpr T_OR AndExpr  */
#line 458 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_OR, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1753 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 41: /* AndExpr: RelExp  */
#line 465 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                 {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1761 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 42: /* AndExpr: RelExp T_AND RelExp  */
#line 468 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_AND, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1769 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 43: /* AndExpr: AndExpr T_AND RelExp  */
#line 471 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                               {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_AND, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1777 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 44: /* RelExp: AddExp  */
#line 480 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		// 加减表达式
		// 直接传递到归约后的节点
		(yyval.node) = (yyvsp[0].node);
	}
#line 1787 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 45: /* RelExp: AddExp RelOp AddExp  */
#line 485 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// 算术表达式 + 关系运算 + 算术表达式
		// 创建关系运算节点，孩子为两个算术表达式节点
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1797 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 46: /* RelExp: RelExp RelOp AddExp  */
#line 490 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// 关系表达式 + 关系运算 + 算术表达式
		// 创建关系运算节点，孩子为关系表达式和算术表达式
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1807 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 47: /* RelOp: T_GT  */
#line 498 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
            {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_GT;
	}
#line 1815 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 48: /* RelOp: T_GE  */
#line 501 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_GE;
	}
#line 1823 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 49: /* RelOp: T_LT  */
#line 504 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_LT;
	}
#line 1831 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 50: /* RelOp: T_LE  */
#line 507 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_LE;
	}
#line 1839 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 51: /* RelOp: T_EQ  */
#line 510 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_EQ;
	}
#line 1847 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 52: /* RelOp: T_NE  */
#line 513 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
               {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_NE;
	}
#line 1855 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 53: /* AddExp: MulExp  */
#line 522 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		// 乘除模表达式
		// 直接传递到归约后的节点
		(yyval.node) = (yyvsp[0].node);
	}
#line 1865 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 54: /* AddExp: MulExp AddOp MulExp  */
#line 527 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// 两个乘除模表达式的加减运算
		// 创建加减运算节点，其孩子为两个乘除模表达式节点
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1875 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 55: /* AddExp: AddExp AddOp MulExp  */
#line 532 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                              {
		// 左递归形式可通过加减连接多个乘除模表达式
		// 创建加减运算节点，孩子为AddExp($1)和MulExp($3)
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1885 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 56: /* AddOp: T_ADD  */
#line 540 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
             {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_ADD;
	}
#line 1893 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 57: /* AddOp: T_SUB  */
#line 543 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_SUB;
	}
#line 1901 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 58: /* MulExp: UnaryExp  */
#line 552 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
		// 一元表达式
		// 直接传递到归约后的节点
		(yyval.node) = (yyvsp[0].node);
	}
#line 1911 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 59: /* MulExp: UnaryExp MulOp UnaryExp  */
#line 557 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                  {
		// 两个一元表达式的乘除模运算
		// 创建乘除模运算节点，其孩子为两个一元表达式节点
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1921 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 60: /* MulExp: MulExp MulOp UnaryExp  */
#line 562 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                {
		// 左递归形式可通过乘除模连接多个一元表达式
		// 创建乘除模运算节点，孩子为MulExp($1)和UnaryExp($3)
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1931 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 61: /* MulOp: T_MUL  */
#line 570 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
             {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_MUL;
	}
#line 1939 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 62: /* MulOp: T_DIV  */
#line 573 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_DIV;
	}
#line 1947 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 63: /* MulOp: T_MOD  */
#line 576 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_MOD;
	}
#line 1955 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 64: /* UnaryExp: PrimaryExp  */
#line 586 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                      {
		// 基本表达式

		// 传递到归约后的UnaryExp上
		(yyval.node) = (yyvsp[0].node);
	}
#line 1966 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 65: /* UnaryExp: T_SUB UnaryExp  */
#line 592 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                         {
		// 求负运算
		
		// 创建求负运算节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_NEG, (yyvsp[0].node));
	}
#line 1977 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 66: /* UnaryExp: T_NOT UnaryExp  */
#line 598 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                         {
		// 逻辑非运算
		
		// 创建逻辑非运算节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_NOT, (yyvsp[0].node));
	}
#line 1988 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 67: /* UnaryExp: T_ID T_L_PAREN T_R_PAREN  */
#line 604 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                   {
		// 没有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-2].var_id).id), (yyvsp[-2].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-2].var_id).id);

		// 实参列表
		ast_node * paramListNode = nullptr;

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参为空，但函数内部会创建实参列表节点，无孩子
		(yyval.node) = create_func_call(name_node, paramListNode);

	}
#line 2009 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 68: /* UnaryExp: T_ID T_L_PAREN RealParamList T_R_PAREN  */
#line 620 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                 {
		// 含有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-3].var_id).id), (yyvsp[-3].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-3].var_id).id);

		// 实参列表
		ast_node * paramListNode = (yyvsp[-1].node);

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参不为空
		(yyval.node) = create_func_call(name_node, paramListNode);
	}
#line 2029 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 69: /* PrimaryExp: T_L_PAREN Expr T_R_PAREN  */
#line 639 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                       {
		// 带有括号的表达式
		(yyval.node) = (yyvsp[-1].node);
	}
#line 2038 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 70: /* PrimaryExp: T_DIGIT  */
#line 643 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                  {
        	// 无符号整型字面量

		// 创建一个无符号整型的终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].integer_num));
	}
#line 2049 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 71: /* PrimaryExp: LVal  */
#line 649 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                {
		// 具有左值的表达式

		// 直接传递到归约后的非终结符号PrimaryExp
		(yyval.node) = (yyvsp[0].node);
	}
#line 2060 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 72: /* RealParamList: Expr  */
#line 661 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                     {
		// 创建实参列表节点，并把当前的Expr节点加入
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
	}
#line 2069 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 73: /* RealParamList: RealParamList T_COMMA Expr  */
#line 665 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                     {
		// 左递归增加实参表达式
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 2078 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 74: /* LVal: T_ID  */
#line 672 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
            {
		// 变量名终结符

		// 创建变量名终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].var_id));

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 2092 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 75: /* LVal: ArrayAccess  */
#line 681 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                      {
		// 数组访问表达式
		(yyval.node) = (yyvsp[0].node);
	}
#line 2101 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 76: /* ArrayDimensions: T_L_BRACKET T_DIGIT T_R_BRACKET  */
#line 688 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                  {
		// 一维数组
		ast_node * dim_node = ast_node::New((yyvsp[-1].integer_num));
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIMENSIONS, dim_node);
	}
#line 2111 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 77: /* ArrayDimensions: T_L_BRACKET T_R_BRACKET  */
#line 693 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                  {
		// 空维度数组（用于函数形参）
		ast_node * dim_node = ast_node::New(digit_int_attr{0, yylineno}); // 使用0表示空维度
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIMENSIONS, dim_node);
	}
#line 2121 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 78: /* ArrayDimensions: ArrayDimensions T_L_BRACKET T_DIGIT T_R_BRACKET  */
#line 698 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                          {
		// 多维数组，左递归添加维度
		ast_node * dim_node = ast_node::New((yyvsp[-1].integer_num));
		(yyval.node) = (yyvsp[-3].node)->insert_son_node(dim_node);
	}
#line 2131 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 79: /* ArrayDimensions: ArrayDimensions T_L_BRACKET T_R_BRACKET  */
#line 703 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                  {
		// 多维数组的空维度
		ast_node * dim_node = ast_node::New(digit_int_attr{0, yylineno}); // 使用0表示空维度
		(yyval.node) = (yyvsp[-2].node)->insert_son_node(dim_node);
	}
#line 2141 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 80: /* ArrayAccess: T_ID T_L_BRACKET Expr T_R_BRACKET  */
#line 711 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                {
		// 一维数组访问
		ast_node * var_node = ast_node::New((yyvsp[-3].var_id));
		free((yyvsp[-3].var_id).id);
		
		// 创建数组访问节点，包含数组名和索引表达式
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_ACCESS, var_node, (yyvsp[-1].node));
	}
#line 2154 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 81: /* ArrayAccess: ArrayAccess T_L_BRACKET Expr T_R_BRACKET  */
#line 719 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"
                                                   {
		// 多维数组访问，左递归添加索引
		(yyval.node) = (yyvsp[-3].node)->insert_son_node((yyvsp[-1].node));
	}
#line 2163 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;


#line 2167 "/home/code/exp04-minic-expr/frontend/flexbison/autogenerated/MiniCBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 725 "/home/code/exp04-minic-expr/frontend/flexbison/MiniC.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}
